### ISSUE TITLE
Change repository name to `dirs-next`

### ISSUE THREAD

**Issue by NickHackman** [xdg-rs/dirs#18]
As mentioned on the [Reddit post](https://www.reddit.com/r/rust/comments/gli4pc/directoriesnext_dirsnext_the_new_home_for/fqy8sb3?utm_source=share&utm_medium=web2x) it makes sense to name the repository the same name as the crate, to avoid confusion and easier search-ability.

**Comment by lzutao** [comment]
There are disadvantages:
* It breaks links pointing back to this repository from crates.io and docs.rs .
* This repository is a cargo workspace with `dirs-next` crate at top-level directories. Workspace name `dirs` makes sense to me.

There are some alternative to avoid confusion and improve searching:
* Use github tags dirs-next
* Move dirs-next crate to its own directories.

**Comment by nmccarty** [comment]
We've discussed this in our team meeting and feel that renaming the repository is not currently warranted. 

We are open to revisiting this later if the name mismatch does turn out to cause friction.
