### ISSUE TITLE
Add dirs/directories crates to Comparison grid?

### ISSUE THREAD

**Issue by daboross** [xdg-rs/dirs#20]
The [comparison grid](https://github.com/xdg-rs/dirs#comparison) in the current README documents all directory crates, maintained and unmaintained, except it's now missing dirs and directories. I believe those entries were replaced with dirs-next/directories-next.

Could we re-add entries for dirs/directories for posterity? I feel like they should be there, especially as other unmaintained crates with maintained forks, such as `app_dirs`, are left in.

**Comment by Torrencem** [comment]
I think this is a good idea, take a look at #24 (you can see the new README rendered [here](https://github.com/Torrencem/dirs/tree/new_comparison_grid))

**Comment by sondr3** [comment]
Given that the author of the original crates has archived them and from what a user [claimed](https://old.reddit.com/r/rust/comments/ga7f56/why_dirs_and_directories_repositories_have_been/foyqipp/) on reddit the author was going to archive them until 2022, do we need to keep the old ones in the comparison? Especially as the hope here is that this repo can be the future for those crates.

**Comment by daboross** [comment]
I'd say that it's still useful to include them, as they are still used today in various crates - and having a place in the comparison grid makes it easy to see how they compare to dirs-next/directories-next. Mainly, that they have the same features, and they are unmaintained.

If you want to leave them out, I'd urge that we also then remove `app_dirs` and other unmaintained crates. I don't see any practical difference between the maintenance statuses of `dirs` and `app_dirs`. I would prefer to leave all the unmaintained crates in for a proper comparison, but if we're removing some (dirs/directories), we should remove all of them, no?

**Comment by lzutao** [comment]
We don't list them (dirs and directories) because this repo is a forking of them.
It is listed at the head of the README file.

**Comment by daboross** [comment]
I guess that's OK. I don't think the fact that `dirs-next` forks `dirs` makes any difference, though - `dirs` is still an alternative to use, right?

**Comment by lzutao** [comment]
Redundancy I think in the README file:
> Note: This is a fork of unmaintained dirs crate.

**Comment by daboross** [comment]
At this point it's just bikeshedding. If you think that's a better place for the information to be, and redundancy in this way is bad, that's OK with me.

**Comment by lzutao** [comment]
:) Thanks for bearing with us!
