### ISSUE TITLE
Is there a reason why `cfg-if` is locked to  `0.1.9`?

### ISSUE THREAD

**Issue by ivanceras** [xdg-rs/dirs#30]
```toml
[dependencies]
cfg-if = "=0.1.9"
```

I'm getting an error like:

```log
error: failed to select a version for `cfg-if`.
<..snip..>
versions that meet the requirements `^0.1.10` are: 0.1.10
```

due to one of my dep library is using `cfg-if 0.1.10` while `directories-next` is locked to `0.1.9` version.

**Comment by lzutao** [comment]
We just inherited that when forking dirs from <https://github.com/soc/dirs-rs>.
I think the original author pinned it to keep MSRV at 1.13 which we don't anymore.

There is a PR to remove this pinning: https://github.com/xdg-rs/dirs/pull/26 . I hope to merge it this week, if not could you open a PR to do that?

**Comment by lightclient** [comment]
I'm also having this issue when trying to patch a new version of `rustyline` into `nushell`: https://github.com/nushell/nushell/issues/1867
